`timescale 1ns/1ps

module tb_4_to_1_mux;

    reg [1:0] sel;
    reg [3:0] d;
    wire y;

    mux4to1 uut (
        .sel(sel),
        .d(d),
        .y(y)
    );

    initial begin

        d = 4'b1010;

        sel = 2'b00;
        #10;

        sel = 2'b01;
        #10;

        sel = 2'b10;
        #10;

        sel = 2'b11;
        #10;

        $finish;
    end

endmodule
